### ISSUE TITLE
建议每个字符使用随机的颜色

### ISSUE THREAD

**Issue by toaco** [vcodeclub/graphic-verification-code#2]
因为现在的字符和干扰信息颜色都是固定的,很容易过滤掉干扰信息. 建议不同的字符,不同的信息使用随机的颜色

**Comment by Brightcells** [comment]
@toaco Good Idea

**Comment by Brightcells** [comment]
已支持字符、干扰线、干扰点使用随机颜色：https://github.com/vcodeclub/graphic-verification-code/commit/2873e7a9bb51fc89c0b13c86b5b7e616b45206d8
TODO：每个字符使用随机颜色

**Comment by Brightcells** [comment]
已支持每个字符使用随机颜色：https://github.com/vcodeclub/graphic-verification-code/commit/26483eb26848f26ca7957fdfd987346d8ca9935c

**Comment by Brightcells** [comment]
pip install graphic-verification-code==1.1.1
